Adds postalcode rules and translations for each different country
vtex-apps/checkout-ui-custom pull request #105
Opened 2022-04-21 20:41 UTC by lucasayb

Changes made:
Add the missing country rules for some countries

Goal of this change:
Without some translations, the checkout keeps returning error, which causes the Google Maps Form not to load. The goal of this PR is not to apply the translations, but to mitigate this error by now and then later do the correct translations

2022-04-22 12:11 UTC, lucasayb commented
This PR is related with this one: https://github.com/vtex-apps/checkout-ui-custom/pull/101

2022-04-26 13:39 UTC, lucasayb commented
Any news about this? It's urgent!

2022-05-04 15:38 UTC, albertm805 requested changes
This is a compiled file. We need to add the original file where the changes were applied.

2022-05-06 16:12 UTC, albertm805 commented on checkout-ui-custom/src/_js/_countries.js
> +    postalCode: !0,
Why is this set with a `!`?

2022-05-06 16:12 UTC, albertm805 commented on checkout-ui-custom/src/_js/_countries.js
> +    number: !1,
Here also

2022-05-06 16:20 UTC, lucasayb commented on checkout-ui-custom/src/_js/_countries.js
> +    postalCode: !0,
I assumed it was to allow only numbers.

2022-05-06 16:27 UTC, albertm805 commented on checkout-ui-custom/src/_js/_countries.js
> +    number: !1,
This has to be Boolean

2022-05-11 22:55 UTC, closed without merging

2022-05-11 22:56 UTC, albertm805 commented
PR closed, as this change was merged in another PR