Remove custom form class when it shouldn't be displayed
vtex-apps/checkout-ui-custom pull request #160
Opened 2022-10-10 13:22 UTC by Git-the-Sanz

In some cases, the user lands on the PUP selection and the google address form is rendered. This is due to no statement checking if the class should be removed.

2022-10-10 13:32 UTC, wender approved these changes

2022-10-19 13:50 UTC, Git-the-Sanz commented
Hey @wender! 
I made a new change, I fixed an instance where the GAdressForm was not rendering for a returning user that fills its profile information for the smart checkout.

In another topic, while making that change, the linter began to complain about things that I didn't even modified, so I ran the format script in the package.json and ended with all the prettier changes you see.

2022-11-04 13:42 UTC, wender requested changes
It's missing the Changelog

2022-11-14 15:34 UTC, polishq approved these changes
LGTM

2022-11-14 15:38 UTC, wender approved these changes

2022-11-15 12:11 UTC, merged